# -*- coding: utf-8 -*-
"""Minutes meeting generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wP6ahXDNt5ggw_J6eSnko4-ILZW5nhcZ
"""

import pandas as pd
from datetime import datetime

print("MEETING MINUTUES GENERATOR\n")

#User Inputs
meeting_title = input("Enter meeting title: ")
date = input("Enter meeting date (DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participants (comma-separated): ")
agenda = input("Enter agenda points(comma-separated): ")
decisions = input("Enter decisions taken(comma-separated): ")
action_items = input("Enter action items(comma-separated): ")
prepared_by = input("Enter prepared by: ")

#Process Inputs
participants_list = [p.strip() for p in participants.split(",")if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",")if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",")if d.strip()]
action_list = [a.strip() for a in action_items.split(",")if a.strip()]

#Create structured meeting minutes
minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "Participants": ", ".join(participants_list),
    "Agenda": ", ".join(agenda_list),
    "Decisions": ", ".join(decisions_list),
    "Action Items": ", ".join(action_list),
    "Prepared By": prepared_by,
    "Generated On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}

#Convert to DataFrame
df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])

print("\n Meeting Minutes Generated Sucessfully\n")
display(df)

#Save as CSV
df.to_csv("meeting_minutes.csv", index=False)
print("\n File saved as meeting_minutes.csv")